---
title: "README.md"
author: "Anish"
date: "July 27, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Getting and Cleaning Data Course Project - Goals

1. A tidy data set
2. A link to a Github repository with your script for performing the analysis
3. A code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.
4. run_analysis.R Script

## Getting and Cleaning Data Course Project - Dataset

Human Activity Recognition Using Smartphones Dataset - http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

## Getting and Cleaning Data Course Project - Files

1. CodeBook.md a code book that describes the variables, the data, and processes to tidy the data

2. run_analysis.R performs the data preparation and then followed by the steps required as described in the course project’s definition:
  Step1: Merges the training and the test sets to create one data set.
  Step2: Extracts only the measurements on the mean and standard deviation for each measurement.
  Step3: Uses descriptive activity names to name the activities in the data set
  Step4: Appropriately labels the data set with descriptive variable names.
  Step5: From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
3. FinalData.txt is the exported final data after going through all the sequences described above.
